site_name: Kopi
site_url: https://kopi-vm.github.io/
repo_url: https://github.com/kopi-vm/kopi
theme:
  name: material
  language: en
  font:
    text: Roboto
  logo: assets/logo_black.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  palette:
    primary: brown
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
    - search.suggest
    - search.highlight
  custom_dir: overrides
plugins:
  - search
  - offline
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kopi-vm/kopi

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - First Steps: getting-started/first-steps.md
  - Guide:
      - Managing JDK Versions: guide/managing-versions.md
      - Working with Projects: guide/projects.md
      - Shell Integration: guide/shell-integration.md
  - Concepts:
      - Architecture: concepts/architecture.md
      - Version Files: concepts/version-files.md
      - Shims: concepts/shims.md
      - Metadata System: concepts/metadata.md
  - Reference:
      - Commands: reference/commands.md
      - Configuration: reference/configuration.md
      - Environment Variables: reference/environment.md
      - Exit Codes: reference/exit-codes.md
  - Troubleshooting: troubleshooting.md
