name: Update JDK Metadata

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Kopi
      run: cargo install kopi

    - name: Update metadata
      run: kopi-metadata-gen update --input docs/metadata --output docs/metadata
    
    - name: Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add docs/metadata/index.json
        git add docs/metadata/**/*.json
        git commit -m "Update metadata on $(date -u +"%Y-%m-%d %H:%M:%S UTC")"

        git push origin main
